Remove unnecessary entries in .cfg files
redeclipse/maps pull request #31
Opened 2016-12-23 15:05 UTC by molexted

Applies to 25 maps, saving ~180 KB per map, or about 4.5 MB total
.mpz files included because texturecull requires applicable .mpz files as well (so the map and config have matching texture mappings)

2016-12-23 16:15 UTC, TheAssassin requested changes
How are those shader variable values unnecessary?
Apart from that: You also changed some of the other variables, too (e.g. [this one](https://github.com/red-eclipse/maps/pull/31/commits/ce84ae5e76f1fd8878e6684fb0d1d48046b7efd3#diff-b4fb4ae2406bae500b863d86456b9d89R11)). That's not very atomic, I wouldn't merge this PR.

2016-12-23 16:43 UTC, molexted commented
I didn't manually change them, I think that's just the result of re-saving an old map in a newer version.
It's as atomic as i can get with the current version of the game, I think.

The culled lines are references to the full texture list, when only about 50-100 textures are included in the map. The unnecessary ones were removed with /texturecull.

2016-12-23 16:48 UTC, TheAssassin commented
Well, in that case we don't have to trust your words that this is correct but the code @qreeves wrote. Looks OK to me then.

2016-12-23 16:49 UTC, TheAssassin approved these changes

2016-12-23 20:43 UTC, molexted commented
By the way, this seems to remove the invalid `setpixelparam` setting from the luckystrike-barlight texture that was causing the invalid commands on map load. Since this gets ignored with the current version, this change won't change (or fix) the lack of that shader.

I don't exactly know what `setpixelparam 0 0.800000 0.800000 0.800000 0.000000` does, so I'm not sure how to fix it (revert it to when `setpixelparam` worked)

2016-12-24 04:45 UTC, qreeves requested changes
Need to remove UI variables from map configs.

2016-12-24 04:45 UTC, qreeves commented on absorption.cfg
> +mut = [131072]
These lines are from the loading screen interface and shouldn't be in the map file. I thought I fixed this problem but it still seems to happen.

2016-12-24 14:36 UTC, molexted commented
Forgot about that, should be fixed now.

2016-12-25 04:03 UTC, merged